### ISSUE TITLE
consistent variable usage n_minibatch

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#122]
It would be great to have consistent usage in the code of
n_minibatch/n_samples/num_minibatch etc.

I suggest 
n_samples for number of samples from the variational distribution and
n_minibatch for number of data samples in each iteration

**Comment by dustinvtran** [comment]
A quick search in the code base for `n_` and `num_` gets me the following: `n_iter`, `n_print`, `n_minibatch`, `n_data`, `num_vars`, `num_params`, `num_factors`.

I suggest we rename all of them to use `n_` instead of `num_`. And also as you said, rename `n_samples` to represent the sample size for draws from the variational distribution and `n_minibatch` to represent the mini-batch size for data (i.e., sample size for draws from the population distribution).

**Comment by mariru** [comment]
ok, I'll do that!

**Comment by mariru** [comment]
in model/variationals.py there is also a variable named `size` passed to `vatiational.sample()` I'm renaming it to `n_samples`

**Comment by dustinvtran** [comment]
Hi @mariru: Any additional progress on this? I think we should do this soon to avoid the future confusion that `n_minibatch` will mean number of data samples rather than number of latent variable samples (which it currently does).

**Comment by mariru** [comment]
Done. #162
