### ISSUE TITLE
Example with Keras would be nice

### ISSUE THREAD

**Issue by TJKlein** [blei-lab/edward#124]
Hi there,

there is a bunch of cool examples. However, I am missing an example with Keras. It would be great to have one. I wanted to create a bayesian NN using defining the network architecture using Keras....

Cheers

**Comment by dustinvtran** [comment]
hi @TJKlein. there's a mixture density network example available [here](https://github.com/blei-lab/edward/blob/master/examples/mixture_density_network.py) with an excellent [notebook](https://github.com/blei-lab/edward/blob/master/docs/source/notebooks/MDN_Edward_Keras_TF.ipynb) written by @cbonnett associated with it. It uses Keras for constructing the network architecture in the model.

Unfortunately it's not possible to be Bayesian about network architectures defined in higher-level languages. This is because they don't provide access to the weights as they are stored and accessed internally in the language. To put priors on weights (as in Bayesian NN's), we have to specify them manually.

**Comment by TJKlein** [comment]
Thanks for the quick reply. That's too bad. I saw this [PyMC3 example](https://gist.github.com/anonymous/96b998304de1eb4306738543170788ca) using Lasagne in combination with PyMC3 and was hoping for similar things using Keras :).

**Comment by dustinvtran** [comment]
Yeah we could definitely do it with Lasagne as they allow the weights as input. Perhaps that would be a useful middleground between manually specifying the NN architecture and using Keras to do everything.

**Comment by nbro** [comment]
@dustinvtran The example you mentioned above does not exist anymore (dead link). Can you update the link?
