### ISSUE TITLE
consider renaming sample_noise

### ISSUE THREAD

**Issue by akucukelbir** [blei-lab/edward#145]
`sample_noise` is unintuitive and not descriptive to people who haven't read the key papers.

consider replacing `sample_noise` with `sample_standard` or something that indicates that we are sampling from a fixed / standard / basic random variable in this function.

**Comment by dustinvtran** [comment]
Yeah that makes sense. Descriptively, the function should draw samples from a distribution without using any parameters of the original distribution. `sample_noise()` doesn't necessarily imply this because noise can still have parameters and it's not necessary that the noise doesn't share parameters. I would avoid `sample_standard` because it implies sampling from a standard version of the original random variable, i.e., Normal family -> standard Normal as the base, although it could easily have been Normal family -> uniform(0,1) as the base. Jury still out—thoughts appreciated :)

**Comment by akucukelbir** [comment]
how about `sample_base`

**Comment by dustinvtran** [comment]
That sounds fine. The term is overloaded with base distribution/measure in nonparametrics. I guess you can make an argument that they're doing the same thing?

**Comment by akucukelbir** [comment]
good point. i think it's better than `sample_noise`, though i'm more than happy to hear other thoughts.
