### ISSUE TITLE
Using Edward with Theano backend

### ISSUE THREAD

**Issue by quantlearn** [blei-lab/edward#222]
I am working on a Bayesian inference problem for which Edward looks like a perfect fit.  Unfortunately,  I am restricted (please don't ask why) to using Windows and as you know TensorFlow is not currently supported on Windows.   

Would it be possible without much work to adapt Edward to use Keras with a Theano backend?  

I welcome your thoughts on the matter and would be happy to contribute in any way I can.

**Comment by twiecki** [comment]
Note sure if it's a good fit for you, but `pymc3` uses theano and has some variational inference as well, like ADVI: http://pymc-devs.github.io/pymc3/

**Comment by dustinvtran** [comment]
Yeah that's right, I think you would have to use another library like PyMC3. Edward is deeply entrenched in TensorFlow for the backend computation. 

We had thought about being compatible with multiple backends similar to Keras for example, but we decided against it for maintenance reasons, and also due to a more limited support of backend features. Fortunately, it does look like TensorFlow will support Windows soon, and therefore so will Edward (https://github.com/tensorflow/tensorflow/issues/17).

**Comment by MannyKayy** [comment]
@dustinvtran On your point about being back-end agnostic; I would suggest keeping it in mind for Edwards future. I predict a transition towards next generation deep learning frameworks such as [chainer](http://docs.chainer.org/en/stable/) and [DyNet](lhttp://dynet.readthedocs.io/en/latest/index.html) for complex NN research over the coming years. 

I myself ended up hitting the limitations of current frameworks (TF + Keras) very quickly as i tried to experiment with new paradigms such as **Define-By-Run** dynamic networks (i.e. computation graph is compiled by the forward pass through the NN at every iteration). Rather than continuing my attempts to hack it with current frameworks, I have ended up transitioning to chainer after some experimentation with both it and dynet. It would definitely be useful to have Edward natively support one of these frameworks as DL research branches out in this direction.

Here is another related link if interested:
[Dynet Tutorial](https://github.com/clab/dynet_tutorial_examples)

**Comment by dustinvtran** [comment]
[TensorFlow now supports Windows.](https://github.com/tensorflow/tensorflow/releases/tag/0.12.0-rc0)

**Comment by datnamer** [comment]
@MannyKayy  Doesn't stochastic control flow in Edward help with the dynamic nature you are looking for?
