### ISSUE TITLE
Understanding ``build_reparam_loss``

### ISSUE THREAD

**Issue by bayerj** [blei-lab/edward#304]
Hi,

I am currently reading edward code and found myself struggling with some of the internals of ``build_reparam_loss``. I will just go over some things and place a question here and there.

The function basically computes a stochastic variant of the ELBO. The workhorses are ``log q(z)``, ``log p(z)`` and ``log p(x|z)`` in lines

The user specifies the number of samples to draw, which are then averaged outside of the log to get an estimate of the expected value. For each of the iterations, the random variable representing the latent state is copied (which seems to be similar to Theano's ``clone`` function) to obtain a sample.

**Question:** Is that copy efficient? It seems as if quite a lot of the graph will be copied as well. Wouldn't obtaining samples via ``qz.sample(n_samples)`` be more efficient, as it allows to perform vectorized computations?

The calculation of the log-probability of the prior and the likelihood function are different for inference methods where a ``model_wrapper`` attribute is present and where there is not. 

**Question:** Where can I find out what ``model_wrapper`` does? Grepping the source code was not turning up useful infos immediately.

After that, the terms are added and yielded for further processing.

**Comment by dustinvtran** [comment]
Yup, the `copy` has the same functionality as Theano's `clone`. 

In general, graph copying is necessary because a model is explicitly represented under a computational graph. For example, a joint of `p(z) p(x | z)` is built in the graph as `z -> x`, where `x` is parameterized by a sample from `z` ([sparse details of that documented here](http://edwardlib.org/api/model)). During inference, say we want to calculate the likelihood `p(x | z^{(s)}`, where `z^{(s)}` is a sample from another distribution `q(z; lambda)`. To do this, we have to copy `x` and replace its parent of `z` with its parent of `qz`.¹

__Q1.__ 
That's right. `qz.sample(n_samples)` would more efficient in that it vectorizes over the number of samples. In general, the issue is that it's unknown how to vectorize the procedure for ancestral sampling. For example, say we define the distributions,
```python
z = Normal(mu=0.0, sigma=1.0)
x = Normal(mu=tf.ones(50) * z, sigma=1.0)
```
To get 5 samples, we'd like to do `z.sample(5)` followed by a vectorized `x_vec.sample()`, where `x_vec` has the shape `(5, x.get_shape())`. However, creating this `x_vec` with something like `copy(x, {z: z.sample(5)})` will raise an error: it tries to parameterize `x` with a multiplication of a 50-vector and a 5-vector. It would only work if all random variable dependencies are written vectorized, such as
```python
x = Normal(mu=tf.tile(z, [50] + z.get_shape().as_list()), sigma=1.0)
```
(In practice, the number of samples is at most 5-10, so vectorization isn't a big issue.)

__Q2.__
You can find details about model wrappers [here](http://edwardlib.org/api/model). They have somewhat limited structure in that they can only compute log joint densities (and minor extensions). They may end up being removed in an Edward 2.0 in order to simplify the code base. 

[1] As you said, this can make graph construction during inference somewhat expensive. An alternative that @matthewdhoffman and I explored was defining the probability model on a metagraph. This delays creation of any tensors until inference when we actually know how to connect up the random variables for computation. However, this runs into many problems: one is essentially having to define your own tensor operations at the metagraph level.

**Comment by bayerj** [comment]
Thanks for the explanations. It is making sense now.

I suppose it will be apparent in the future if graph construction does not scale enough and makes some applications unrealistic.

**Comment by junpenglao** [comment]
@dustinvtran 
Thank you for the great work on the package. I am also trying to understand the underlying mechanics of edward and come across this post.

You mentioned:
> (In practice, the number of samples is at most 5-10, so vectorization isn't a big issue.)  

Is there some reference for that? Is the 5-10 samples works also for large model with lots of parameters?
