### ISSUE TITLE
make setting the number of iterations easy

### ISSUE THREAD

**Issue by mariru** [blei-lab/edward#387]
The following two statement execute `inference.update()` the default number of time (n_iter = 1000)

```
inference.initialize(n_iter=10000)
inference.run()
```

```
inference.n_iter=10000
inference.run()
```

It would be great if `inference.initialize()` checks if ``n_iter` is already defined.

**Comment by dustinvtran** [comment]
that does sound convenient. i think it's doable by giving a initialize flag to inference, so that `inference.run()` will only initialize if the flag is False. 

a bigger interface issue then is what to do with the rest of `inference.run()`. should `inference.run()` always initialize TensorFlow variables? should it always start and stop queue runners?  the `finalize()` step?
