### ISSUE TITLE
Questions about Edward and Stan

### ISSUE THREAD

**Issue by yyaodong** [blei-lab/edward#406]
Hi,

I wanted to solve a compound Poisson Gamma model via BBVI, and after doing some researches on the web, two questions make me really confused, I shall appreciate it if you could help to answer:

1 Edward seems to focus more on the BBVI methods, whereas PyMC / Stan focus more on ADVI methods. The two VI methods seem to be different, but in terms of the tools (Edward vs PyMC/Stan), are they actually mutually exclusive when one tries to apply VI? In general, will the performance of BBVI always be worse than ADVI (because of the high variance)?

2 BBVI needs more attention on the variance control techniques, I wanted to know if anything as the _baseline trick_ has been implemented in Edward? 

Many thanks!

**Comment by dustinvtran** [comment]
1. it could be helpful to clarify the techniques involved in what you're calling "ADVI" and "BBVI". specifically, we use reparameterization gradients (the gradient in "ADVI") if the variational distribution is reparameterizable, and otherwise default to score function gradients (the gradient in "BBVI"). for example, `ed.KLqp` uses reparameterization gradients for normal variational approximations and score function gradients for gamma variational approximations. we don't have automated transformations in yet, so there's no ADVI for always using normal approximations on unconstrained-transformed spaces. automated transformations is a high priority on my list of things to do at the moment.
2. it's a feature request (https://github.com/blei-lab/edward/issues/4); contributions are welcome of course.

happy to answer additional questions.

**Comment by yyaodong** [comment]
Thanks for the quick reply. I think it makes things really clear now.

My follow-up question would be, in the Hierarchical model, if the local latent variables follow discrete distributions, e.g., Poisson, are there any methods in the "ADVI" side that people can use? Or BBVI is probably the only solution.

Thanks a lot !

**Comment by dustinvtran** [comment]
unfortunately no. the ADVI algorithm only works for differentiable probability models (see Table 1 of https://arxiv.org/abs/1603.00788). the score function gradient is more general at the cost of being slower in many models in practice.

**Comment by yyaodong** [comment]
Really thanks for the answers, very enlightening.
