### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by Javihaus** [blei-lab/edward#446]
Hi Dustin/all, here is the complete code:

[Water-1-Copy1.pdf](https://github.com/blei-lab/edward/files/761907/Water-1-Copy1.pdf)

**Comment by Javihaus** [comment]
Data set are historical rainfall per year an the values are between 400 and 1000. Inference finds mus with very low values

**Comment by dustinvtran** [comment]
from your code, you need to call `mu.eval()` after inference. there's no reason to expect that the plot is any different the second time since `outputs` hasn't changed.

as an aside, i also recommend running inference for a few hundered more iterations. doesn't look like it converged. hope that helps!

**Comment by dustinvtran** [comment]
closing as above solves it.
