### ISSUE TITLE
Is there edward of C++ version ?

### ISSUE THREAD

**Issue by artzers** [blei-lab/edward#511]
Hello, I wonder whether there is a edward of C++ version. 
Sometimes programmers may apply tensorflow of C++ version to a more complicated system. C++ version may be helpful.

**Comment by dustinvtran** [comment]
That's a great question. In principle, yes this is possible. Because Edward is basically just a composition of TensorFlow ops, we can put its graph building at a lower level in order to harness other language APIs that TensorFlow offers (such as C++). For this to be practical, we would need to design decisions about the model, inference, and criticism interfaces for each new language.

This undertaking is not on my personal plans for a long time. Maintenance would be more costly than the advantages it offers IMO.

**Comment by dustinvtran** [comment]
Moving discussion to http://discuss.edwardlib.org/t/is-there-edward-of-c-version/26
