### ISSUE TITLE
MixtureGaussian example

### ISSUE THREAD

**Issue by abojchevski** [blei-lab/edward#73]
1. Any idea why the MixtureGaussian example is running slow? Couldn't we vectorize some of the code? For example instead of `for k in range(K):` we should do it for each k in the vector then call `tf.reduce_sum`.

2. More importantly it's nor clear how one can extract the learned parameters to do predictions. In other words once I've run the inference how would I predict for a new data point to which cluster it belongs?

Also I see you used `xrange` which is not Python 3 compatible, not sure if you plan on supporting python 3 at all but just something to keep in mind.

**Comment by dustinvtran** [comment]
1. Yeah this would work if the distributions we wrote enable vector inputs (which I have not verified). My guess is also yours that it's slow primarily because of these loops.

2. Good point. In this example the aim is strictly to track progress of the posterior parameters and the log-likelihood estimate from variational inference. Most interesting downstream tasks would require manually saving the output of `inference.run()` which is the TensorFlow session. (The most idiomatic TensorFlow example is [here](https://github.com/blei-lab/edward/blob/master/examples/normal_idiomatic_tf.py)). I agree that it's not clear. We should have an example that better demonstrates this and is part of the demonstration/tutorial.

Also good point about `xrange`; we should be doing a better job to make things Python 3 compatible as we write rather than leave it as an open Github issue. :)

**Comment by datnamer** [comment]
There is also numba, a fast python JIT: https://github.com/numba/numba 

It is really good at accelerating loopy numerical code to fortran speeds. 

Also +1 to python 3 compat :)

**Comment by dawenl** [comment]
I would hold on adding too much performance-related dependencies (e.g. numba) to the table. Many people (me included) had difficulty getting it to accelerate properly, especially if you are not using conda. But on the other hand, I agree at some point, we should try to vectorize the heck out of the current code (scipy.stats mostly supports vectorized input).

**Comment by datnamer** [comment]
Was this recently? The team has very much improved the breadth of it's API lately.

**Comment by dustinvtran** [comment]
Yeah it's useful to reduce the amount of dependencies. If it turns out to be helpful in practice, we can include it as an optional dependency for running the example scripts, much like `pystan` and `pmyc3` being optional dependencies. We can think about `numba` if the vectorized version for TensorFlow turns out not to be fast enough.

**Comment by abojchevski** [comment]
I was thinking more of doing some manipulations on indices so that instead of writing:
* for each k
* calculate the likelihood of a multivariate_normal given this k-th mus and sigmas
* add it to the sum

to do a single step where we calculate all K multivariate_normal likelihood at the same time, and then call reduce sum on that.

But some playing around with numpy/scipy doesn't suggest it's possible. That is, you can calculated the logpdf for N points at the same time, but you can't calculate the logpdf at the same time for N points and K different means and sigmas. 

In any case the for loop is always small (that is K is small). I guess it's slow because of the other thing you mentioned. Those that mean any model I run with MFVI inference will be slow?

**Comment by abojchevski** [comment]
For a hard cluster assigment after learning the varitional parameters what I ended up doing is:
* calculate the mode of the variational distribution for the k mus
* calculate the mode of the variational distribution for the k sigmas
* calculate the likelihood that a [new] point belongs to cluster k using the above 2
* assign the point to the cluster with the highest likelihood

I just had to do sess.run([variational.layer[1].m]) for example to get the learned params and calculate the mode. Which was not clear immediately but eventually figured it out. I can post a nice notebook example when i get a chance.

**Comment by dustinvtran** [comment]
Yes that would be extremely helpful! The library's quite new and we've been making slow but sure progress on documentation and tutorials.

**Comment by dawenl** [comment]
@datnamer It's been a while. But I think the problematic part is to have LLVM properly installed/configured to be useable. Maybe next time I need to do something fast with for-loop, I will re-visit it.

**Comment by dustinvtran** [comment]
The new vectorized version has gotten it to be much faster—so I'm closing this issue.
