### ISSUE TITLE
Edward unsupervised.ipynb tutorial - error

### ISSUE THREAD

**Issue by Arvinds-ds** [blei-lab/edward#762]
In Edward tutorials,  the` Unsupervised.ipynb` notebook (https://github.com/blei-lab/edward/blob/master/notebooks/unsupervised.ipynb) has the following code (commented)  but I noticed errors

1. `sigma = InverseGamma(tf.ones(D), tf.ones(D), sample_shape=K)`
    `components = [
    MultivariateNormalDiag(mu[k], sigma[k], sample_shape=N)
    for k in range(K)]`

 should be
 ` sigmasq = InverseGamma(tf.ones(D), tf.ones(D), sample_shape=K)`
 `components = [
    MultivariateNormalDiag(mu[k], tf.sqrt(sigmasq[k]), sample_shape=N)
    for k in range(K)]`

2. Uncommenting the code does not work with the Gibbs sampler as behavior of 
`Mixture` is different from` ParamMixture`

So we could remove the code or keep the corrected and commented code with proper inference for the integrated case.

**Comment by dustinvtran** [comment]
Good catch. It's useful to have in order to distinguish how you would distinguish writing a collapsed mixture of Gaussians vs a uncollapsed mixture of Gaussians in practice. Since the Gibbs sampler doesn't work for `Mixture`, we should add a comment about this and suggest another algorithm if you use this version.

**Comment by siddharth-agrawal** [comment]
@dustinvtran Sorry for doing this again, this should be closed.

**Comment by dustinvtran** [comment]
No problem. Thanks for catching these! :)
